### ISSUE TITLE
accurate parsing of accept header

### ISSUE THREAD

**Issue by vlet** [khrt/Raisin#11]
By default jquery send this accept header:
`application/json, text/javascript, */*; q=0.01`

Raisin return "Invalid accept header" error, because it expects only one media type

**Comment by vlet** [comment]
https://github.com/vlet/Raisin/commit/e55f59a7035e2716fcc9fc6b0cf3a68006b2b938

**Comment by khrt** [comment]
Please put this changes into a different branch and send a pull request. Thanks.

**Comment by khrt** [comment]
merged
