### ISSUE TITLE
List::Util dependency

### ISSUE THREAD

**Issue by vlet** [khrt/Raisin#13]
I've tried to build deb package for Ubuntu Server 14.04 LTS and ran into problem: `pairs` function available only in List::Util ≥ 1.29. I can't upgrade List::Util, because it is a part of perl-base package in Ubuntu.
`pairs` used only in one place at Raisin/Routes.pm and can be replaced with `splice` (since temporary array created in any case). I've built patched libraisin-perl and seems like it works for me. May be pairs simplicity is not worth packaging problems on major stable distribution?

**Comment by khrt** [comment]
Actually `splice` doesn't fit here because `%params` should stay untouched there, while `splice` modifies the original data.

But anyway I'll get rid of the dependency in the next release.

Thanks.
