### ISSUE TITLE
Problem with Content-Type

### ISSUE THREAD

**Issue by losyme** [khrt/Raisin#15]
Hello,
The function Raisin::Util::detect_serializer does not support this value of Content-Type:
application/json; charset=UTF-8

**Comment by losyme** [comment]
Hello,

Thanks for your prompt response.



2016-02-18 9:12 GMT+01:00 Artur Khabibullin <notifications@github.com>:

**Comment by renatocron** [comment]
This issue came back to existence in some refactoring. I'm having same problem using 0.73.

**Comment by khrt** [comment]
@renatocron could you provide examples please?
