### ISSUE TITLE
Missing SecurityDefinitionsObject on Raisin::Plugin::Swagger

### ISSUE THREAD

**Issue by 7ojo** [khrt/Raisin#20]
Hello,

I see no documentation about security object definition, but I see there are some commented lines on the code: 

``` perl
    my %spec = (
        swagger  => '2.0',
        info     => _info_object($app),
        host     => $req->env->{HTTP_HOST},
        basePath => $base_path,
        schemes  => [$req->scheme],
        consumes => \@content_types,
        produces => \@content_types,
        paths    => _paths_object($routes), #R
        definitions => _definitions_object($routes),
        #parameters => undef,
        #responses => undef,
        #securityDefinitions => undef,
        #security => undef,
        tags => _tags_object($self->app),
        #externalDocs => '', # TODO
    );
```

So is there some plans adding support or thoughts about security definitions on OpenAPI spec?

Personally I'll be needing api_key, but trying to figure it out how to implement it with Raisin :) Code examples on authentication also are very welcome.

Loving this simplicity of Raisin 👍  Little of coding and you have working REST api

Best regards, Jarkko

**Comment by khrt** [comment]
Going to be added in the next release. Thanks for the report.

**Comment by khrt** [comment]
Please the POD https://metacpan.org/pod/release/RTKH/Raisin-0.69/lib/Raisin/Plugin/Swagger.pm
