### ISSUE TITLE
Boolean and JSON

### ISSUE THREAD

**Issue by LittleFox94** [khrt/Raisin#22]
Using Boolean params with JSON does not work because the validation fails. JSON returns JSON::true/JSON::false for true/false values, so these may not be recognized by the validator.

Idea for solution:
Convert JSON::true/JSON::false values in Bool type parameters to 1/0 before validating them.

**Comment by khrt** [comment]
It's hard to say something with no context but I think it shouldn't be fixed somewhere in the framework. If I understand your issue you should use proper type to validate your values.

You can extend a `Bool` type from `Types::Standard`, please check this manual https://metacpan.org/pod/Moose::Manual::Types

Hope it will help you.

**Comment by LittleFox94** [comment]
OK I will check - thank you (also for the other bugs) :)

I still think this is something the framework should do (even if just giving a proper Bool type) because this will imho affect other users trying to have bool parameters with JSON serialization.

Or is this something that only affects me?

**Comment by khrt** [comment]
It should affect everyone who use boolean values. It's how JSON module
works so I think there is nothing to do with the framework.

Buy just to clarify the case could you please describe what do you do more
detailed?

ak

**Comment by LittleFox94** [comment]
Being a new user to this Framework, first thing I tried to do was something like this (out of my head):

```perl
resource foo => sub {
    params(optional('bar', type => Bool, desc => 'Boolean value', default => 0));
    post sub {
        # do something
    };
};
```

Writing it like this, the parameter never got to my code because it was flagged as invalid and removed from the params. My client delivered data as application/json.

As far as I understand, this is because of the non-Raisin types which are for plain perl usage and not JSON compatible. I can of course implement the correct type for my self, but I think this would be useful for all users (well, those who are using bool parameters).

I hope I don't confuse something here. :D
