### ISSUE TITLE
access to json serializer?

### ISSUE THREAD

**Issue by pryankster** [khrt/Raisin#24]
This might not be a bug, there doesn't seem to be a way to access the json serializer to configure it (for example, to enable convert_blessed()

**Comment by khrt** [comment]
I'm already working on a brand new formatting modules for the framework, so in the nearest future it will be fixed.

**Comment by pryankster** [comment]
That would be awesome, but any suggestions for the most Raisin friendly way to output blessed objects now?

**Comment by khrt** [comment]
Unfortunately I can recommend only to override `Raisin::Plugin::Format::JSON::serialize`.

**Comment by khrt** [comment]
You can register your own serializer, please check following links: 
https://metacpan.org/pod/release/RTKH/Raisin-0.70/lib/Raisin.pm#register_encoder
https://metacpan.org/source/RTKH/Raisin-0.70/lib/Raisin/Encoder/JSON.pm
