### ISSUE TITLE
Raisin in 5.10

### ISSUE THREAD

**Issue by jwrightecs** [khrt/Raisin#27]
In 5.10,  split in scalar context still split to @_, which was removed in 5.12, this affects, at least, Raisin/Middleware/Formatter.pm@65, which throws the deprecation warning when run on 5.10/5.10.1
Use of implicit split to @_ is deprecated at /lib/perl5/Raisin/Middleware/Formatter.pm line 65.

**Comment by khrt** [comment]
Thanks for the report
