### ISSUE TITLE
How to return 404?

### ISSUE THREAD

**Issue by djzort** [khrt/Raisin#30]
When an object/element/whatever doesnt exist, whats the proper way of returning a 404?

For example, with:
`curl localhost:5000/user/:id`
If there is no user with that ID, i would like to return a 404 - which i believe is the most correct behaviour for rest

**Comment by khrt** [comment]
Hi,

you can set like this:

` res->status(HTTP_NOT_FOUND);`

For more see https://github.com/khrt/Raisin/blob/7e87f974887a8e30b3a74a6582aff11605e6aeb3/examples/pod-synopsis-app/darth.pl#L99
