### ISSUE TITLE
Serialize JSON

### ISSUE THREAD

**Issue by beccon4** [khrt/Raisin#58]
Ist there an easier way to return Perl objects (blessed or Moose) than to
- change the lib/Raisin/Encoder/JSON.pm to accomodate allow_blessed->convert_blessed->en/decode
- implement or inherit a TO_JSON serializing function in each object to be returned.

Returning blessed objects to YAML seems to work out of the box. JSON support for plain hashes is also implemented in Raisin. 

But perhaps I'm missing the direct path.

**Comment by khrt** [comment]
If I understand your question correctly, there is no way expect of patching Raisin/Encoder/JSON
