### ISSUE TITLE
Undeclared dependency JSON.pm

### ISSUE THREAD

**Issue by eserte** [khrt/Raisin#70]
Another undeclared dependency:
```
...
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: ... .) at t/behaviour/app-deserialize.t line 7.
BEGIN failed--compilation aborted at t/behaviour/app-deserialize.t line 7.
t/behaviour/app-deserialize.t ......... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
... (etc) ...
```

**Comment by djzort** [comment]
It should probably be swapped to JSON::MaybeXS to match the rest of the dist

**Comment by khrt** [comment]
Should be fixed by now.

I've replaced `JSON` with `JSON::MaybeXS` and also updated `cpanfile` with missing dependencies.

Feel free to reopen if still doesn't work.
