### ISSUE TITLE
The darth.pl example can't post new users, missing max().

### ISSUE THREAD

**Issue by hartzell** [khrt/Raisin#9]
The darth.pl example explodes when one tries to post a new user (via the swagger sandbox).

The script seems to be missing a definition for a max() function.

Adding

```perl
use List::Util qw(max);
```

e.g. after line 12 seems to fix it.

I'm using

```
allons:~ USERNAME$ perl -v

This is perl 5, version 18, subversion 4 (v5.18.4) built for darwin-2level
```

on a mac running OS X 10.9.5.

I set up my test environment via

```
allons:~ USERNAME$ cpanm -l ~/tmp/raisin-experiment Raisin
```

and ran the demo like this:

```
allons:~ USERNAME$ env PERL5LIB=/Users/USERNAME/tmp/raisin-experiment/lib/perl5 PATH=/Users/USERNAME/tmp/raisin-experiment/bin:$PATH plackup ~/.cpanm/latest-build/Raisin-0.58/examples/pod-synopsis-app/darth.pl
```

g.

**Comment by khrt** [comment]
Thanks for the report.
