### ISSUE TITLE
Please include VERSION in all modules

### ISSUE THREAD

**Issue by djzort** [khrt/Raisin#96]
VERSION isnt defined in ::API so i cant go

use Raisin::API 0.89;

This should just be a matter of tweaking the dist.ini

Im happy to send a PR, but wanted to discuss it first

**Comment by khrt** [comment]
Hi @djzort,

please send a PR, I would appreciate this!

**Comment by djzort** [comment]
Ive send a PR. I got more carried away than i intended

**Comment by khrt** [comment]
Thanks a lot! Merging it now.

**Comment by khrt** [comment]
Fixed by #97
