### ISSUE TITLE
Authentication module in Raisin

### ISSUE THREAD

**Issue by AbhishekSharma20** [khrt/Raisin#98]
I couldn't find any way to add authentication to the API built by Raisin. Is there any way I can do it using an external library ? I could see in older cpan documentation there was a section for authentication which is TODO. But in the newer version that section is removed.

**Comment by djzort** [comment]
Would one of the Plack::Middleware::Auth:: modules provide what you are after?
I will defer though to @khrt for his definitive answer.

**Comment by khrt** [comment]
Hi everyone,

I would indeed would delegate the work to a middleware, and what @djzort suggests is a good choice/start.

**Comment by AbhishekSharma20** [comment]
Hi @djzort  @khrt ,
Thanks for the info, This is what I was looking for. Appreciate your help.
